import 'tui-pagination/dist/tui-pagination.css';
import './sass/main.scss';
import './js/test';
import './js/modal';
import './js/team-modal';
import './js/api/fetch_movies';
import './js/base/render';
import './js/render_popular_movies';
import './js/pagination';
import './js/auth-modal';
import './js/authentication';
import './js/search-film';
import './js/scroll';
// import './js/base/loader';
import './js/base/loading';
import './js/theme-dark';